stages:
#  - test
  - build
  - deploy

#test:
#  image: node:12
#  stage: test
#  tags:
#    - abby
#  allow_failure: true
#  when: always
#  script:
#    - yarn install
#    - yarn test

build:
  image: docker:19.03.13-dind
  tags:
    - abby
  stage: build
  when: on_success
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker system info | grep -E 'Username|Registry'
    - docker build -t my-express-app:building .
#    - docker tag my-express-app:building abbylow/cicd-demo:$CI_COMMIT_SHORT_SHA
    - docker tag my-express-app:building abbylow/cicd-demo:latest
#    - docker push abbylow/cicd-demo:$CI_COMMIT_SHORT_SHA
    - docker push abbylow/cicd-demo:latest

one-last-step:
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [ "" ]
  stage: deploy
  when: on_success
  tags:
    - abby
  script:
    - export KUBECONFIG=$config
    - kubectl config current-context
    - kubectl config get-clusters
    - kubectl apply -f ./deployment.yaml
    - kubectl rollout status deploy/cicd-demo
