include:
  - cicd/auto_test.yml
  - cicd/package_ci.yml
  - cicd/deploy_dev.yml

stages:
  - test
  - package
  - deploy

variables:
  REGISTRY_HOST: hub.docker.com

#.build_files_artifact:
#  artifacts:
#    paths:
#      - dist/
#    expire_in: 12 hours
#
#.build_files_cache:
#  cache:
#    key: build_files
#    paths:
#      - node_modules/

.base_test:
  image: node:12
  stage: test
  tags:
    - abby
  allow_failure: false
  when: always

#.base_build:
#  extends:
#    - .build_files_cache
#    - .build_files_artifact
#  image: node:12
#  stage: build
#  tags:
#    - abby
#  allow_failure: false
#  when: manual

.base_package:
  image: docker:19.03.13-dind
  tags:
    - abby
  stage: package
  allow_failure: false
  when: manual

.base_deploy:
  image: bitnami/kubectl
  stage: deploy
  allow_failure: false
  tags:
    - abby
