include:
  - cicd/build_ci.yml
  - cicd/auto_test.yml
  - cicd/package_ci.yml
  - cicd/deploy_dev.yml

stages:
  - build
  - test
  - package
  - deploy

variables:
  REGISTRY_HOST: hub.docker.com

.build_files_cache:
  cache:
    key: build_files
    paths:
      - node_modules/

.base_test:
  stage: test
  tags:
    - delly
  allow_failure: false
  when: manual

.base_build:
  extends:
    - .build_files_cache
  image: node:12
  stage: build
  tags:
    - delly
  allow_failure: false
  when: manual

.base_package:
  extends:
    - .build_files_cache
  image: docker:19.03.13-dind
  tags:
    - delly
  stage: package
  allow_failure: false
  when: on_success

.base_deploy:
  image: hub.docker.com/hipay/gitlab-ci-base:buster
  stage: deploy
  before_script:
    - chmod +x run.sh
  allow_failure: false
